version: '4'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contact_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
#      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"

#  contact-app:
#    image: localhost:5001/contact-app:latest
#    container_name: contact_container
#    ports:
#      - "80:8080"
#    depends_on:
#      - postgres
#      - redis

