spring:
  application:
    name: contact

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/contact_db
    username: postgres
    password: postgres

  redis:
    host: redis
    port: 6379

contact-group:
  max-count: 100
  name-length: 100